---
- name: Adds Python PostgreSQL support
  apt:
    name:
      - python3-psycopg2
    state: present

- name: Copy postgresql.conf config file
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/14/main/postgresql.conf
    mode: '644'
  notify:
    - restart postgresql service

- name: Copy pg_hba.conf config file
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
    mode: '644'
  notify:
    - restart postgresql service
