---
- name: Update repo cache and install a few prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - gnupg2

- name: Add official PostgreSQL Server package authentication key
  apt_key:
    data: "{{ lookup('file', 'postgresql_pubkey.asc') }}"
    state: present

- name: Add the PostgreSQL Server repository to APT sources
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: postgresql
    mode: '0644'
  with_items:
    - "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"

- name: Install/Update PostgreSQL Server
  apt:
    update_cache: true
    name: postgresql-14
    state: present

- name: Start and enable PostgreSQL Server
  service:
    name: postgresql
    state: started
    enabled: true
