---

- name: include_vars for auriga
  include_vars: "~/cloudstarter/inventory/group_vars/auriga_pg.yml"
  when: type_vm == "auriga"

- name: Include ./install.yml
  ansible.builtin.import_tasks: install.yml
  tags:
    - install_postgresql
    - install

- name: Include ./configure.yml
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configure_postgresql
    - configure
